/**
 * subagent 定義 (agents/subagents/*.md) を Codex と OpenCode の形式へ変換する。
 *
 * 正本は Claude Code 形式の Markdown + frontmatter で、Codex は TOML、OpenCode は
 * 別スキーマの Markdown を要求するため、書式変換だけが避けられない。変換を呼ぶのは
 * build-harness.ts で、語彙の置換を当てた後にこの関数群へ渡す (順序が逆だと TOML の
 * 中身に置換をかけることになる)。
 *
 * 3 者で意味が対応しないキーは落とす:
 * - `tools` は Codex に対応キーが無く、OpenCode は真偽値マップで意味が逆になる
 * - `model` は Codex では実モデル名が要り alias が使えない。世代交代に追従できないので
 *   生成物には書かない (固定したければ `agents/bindings/codex/config.toml` の
 *   `[agents] default_subagent_model` に 1 箇所だけ書く)
 * - `context: fork` に相当する概念は Codex にも OpenCode にも無い
 */

/** 生成物であることの目印。prune はこの行を持つファイルだけを撤去する */
export const GENERATED_MARKER =
  "# generated by agents/scripts/build-harness.ts — 手で編集しない";

export type Subagent = {
  frontmatter: Record<string, string>;
  body: string;
};

export function parseSubagent(markdown: string): Subagent {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    throw new Error(`frontmatter が見つかりません: ${markdown.split("\n")[0]}`);
  }
  const frontmatter: Record<string, string> = {};
  for (const line of match[1].split("\n")) {
    const kv = line.match(/^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$/);
    if (kv) frontmatter[kv[1]] = kv[2].trim();
  }
  return { frontmatter, body: match[2].replace(/^\n+/, "") };
}

function requireKey(frontmatter: Record<string, string>, key: string): string {
  const value = frontmatter[key];
  if (!value) throw new Error(`frontmatter に ${key} がありません`);
  return value;
}

/** TOML の basic string。制御文字を含まない前提で `"` と `\` だけ逃がす */
function tomlBasicString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export function toCodexToml(subagent: Subagent): string {
  const name = requireKey(subagent.frontmatter, "name");
  const description = requireKey(subagent.frontmatter, "description");
  if (subagent.body.includes("'''")) {
    throw new Error(
      `${name}: 本文に ''' が含まれるため TOML の literal string に入れられません`,
    );
  }
  const body = subagent.body.endsWith("\n") ? subagent.body : `${subagent.body}\n`;
  return [
    GENERATED_MARKER,
    `name = ${tomlBasicString(name)}`,
    `description = ${tomlBasicString(description)}`,
    `developer_instructions = '''`,
    body + `'''`,
    "",
  ].join("\n");
}

export function toOpencodeMarkdown(subagent: Subagent): string {
  const description = requireKey(subagent.frontmatter, "description");
  const body = subagent.body.endsWith("\n") ? subagent.body : `${subagent.body}\n`;
  return `---\n${GENERATED_MARKER}\ndescription: ${description}\nmode: subagent\n---\n\n${body}`;
}
