#!/usr/bin/env -S deno run --allow-read --allow-write

/**
 * subagent 定義 (agents/subagents/*.md) を Codex と OpenCode の形式へ変換する。
 *
 * 正本は Claude Code 形式の Markdown + frontmatter で、Codex は TOML、OpenCode は
 * 別スキーマの Markdown を要求するため、書式変換だけが避けられない。変換は Nix の
 * activation から実行され、生成物は git 管理しない。
 *
 *   sync-subagents.ts <src-dir> <target> <out-dir>
 *     target: codex | opencode
 *
 * 生成物には GENERATED_MARKER を埋め、prune の対象をマーカー付きファイルに限る。
 * 配布先 (~/.codex/agents / ~/.config/opencode/agents) は人が自分の agent を置く場所でも
 * あるため、拡張子だけで撤去すると手書きファイルを消してしまう。
 *
 * 3 者で意味が対応しないキーは落とす:
 * - `tools` は Codex に対応キーが無く、OpenCode は真偽値マップで意味が逆になる
 * - `model` は Codex では実モデル名が要り alias が使えない。世代交代に追従できないので
 *   生成物には書かない (固定したければ `codex/config.toml` の
 *   `[agents] default_subagent_model` に 1 箇所だけ書く)
 * - `context: fork` に相当する概念は Codex にも OpenCode にも無い
 */

/** 生成物であることの目印。prune はこの行を持つファイルだけを撤去する */
export const GENERATED_MARKER =
  "# generated by agents/scripts/sync-subagents.ts — 手で編集しない";

export type Subagent = {
  frontmatter: Record<string, string>;
  body: string;
};

export function parseSubagent(markdown: string): Subagent {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    throw new Error(`frontmatter が見つかりません: ${markdown.split("\n")[0]}`);
  }
  const frontmatter: Record<string, string> = {};
  for (const line of match[1].split("\n")) {
    const kv = line.match(/^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$/);
    if (kv) frontmatter[kv[1]] = kv[2].trim();
  }
  return { frontmatter, body: match[2].replace(/^\n+/, "") };
}

function requireKey(frontmatter: Record<string, string>, key: string): string {
  const value = frontmatter[key];
  if (!value) throw new Error(`frontmatter に ${key} がありません`);
  return value;
}

/** TOML の basic string。制御文字を含まない前提で `"` と `\` だけ逃がす */
function tomlBasicString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export function toCodexToml(subagent: Subagent): string {
  const name = requireKey(subagent.frontmatter, "name");
  const description = requireKey(subagent.frontmatter, "description");
  if (subagent.body.includes("'''")) {
    throw new Error(
      `${name}: 本文に ''' が含まれるため TOML の literal string に入れられません`,
    );
  }
  const body = subagent.body.endsWith("\n") ? subagent.body : `${subagent.body}\n`;
  return [
    GENERATED_MARKER,
    `name = ${tomlBasicString(name)}`,
    `description = ${tomlBasicString(description)}`,
    `developer_instructions = '''`,
    body + `'''`,
    "",
  ].join("\n");
}

export function toOpencodeMarkdown(subagent: Subagent): string {
  const description = requireKey(subagent.frontmatter, "description");
  const body = subagent.body.endsWith("\n") ? subagent.body : `${subagent.body}\n`;
  return `---\n${GENERATED_MARKER}\ndescription: ${description}\nmode: subagent\n---\n\n${body}`;
}

const RENDERERS = {
  codex: { render: toCodexToml, extension: ".toml" },
  opencode: { render: toOpencodeMarkdown, extension: ".md" },
} as const;

type Target = keyof typeof RENDERERS;

async function main(args: string[]) {
  const [srcDir, target, outDir] = args;
  if (!srcDir || !target || !outDir || !(target in RENDERERS)) {
    console.error("usage: sync-subagents.ts <src-dir> <target: codex|opencode> <out-dir>");
    Deno.exit(2);
  }
  const { render, extension } = RENDERERS[target as Target];

  await Deno.mkdir(outDir, { recursive: true });
  const generated = new Set<string>();
  for await (const entry of Deno.readDir(srcDir)) {
    if (!entry.isFile || !entry.name.endsWith(".md")) continue;
    const subagent = parseSubagent(await Deno.readTextFile(`${srcDir}/${entry.name}`));
    const outName = `${requireKey(subagent.frontmatter, "name")}${extension}`;
    await Deno.writeTextFile(`${outDir}/${outName}`, render(subagent));
    generated.add(outName);
  }

  // 正本から消えた subagent の生成物を撤去する。配布先は人が自分の agent を置く
  // 場所でもあるので、拡張子ではなく GENERATED_MARKER の有無で自分の生成物だけを選ぶ。
  for await (const entry of Deno.readDir(outDir)) {
    if (!entry.isFile || !entry.name.endsWith(extension)) continue;
    if (generated.has(entry.name)) continue;
    const content = await Deno.readTextFile(`${outDir}/${entry.name}`);
    if (content.includes(GENERATED_MARKER)) await Deno.remove(`${outDir}/${entry.name}`);
  }
}

if (import.meta.main) {
  await main(Deno.args);
}
