[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

#[[plugins]]
#repo = 'airblade/vim-gitgutter'

#[[plugins]]
#repo = 'prabirshrestha/async.vim'
#
#[[plugins]]
#repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'md'

[[plugins]]
repo = 'tpope/vim-surround'

#[[plugins]]
#repo = 'vim-airline/vim-airline'
#
#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'tpope/vim-repeat'
on_idle = 1

[[plugins]]
repo = '/usr/local/opt/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'SirVer/ultisnips'
on_ft = 'go'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'maralla/completor.vim.git'

#[[plugins]]
#repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'vim-scripts/dbext.vim'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'nonylene/vim-keymaps'
