# Go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

# language server protocol
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

# async auto complete
[[plugins]]
repo = 'prabirshrestha/async.vim'
merged = 0

#[[plugins]]
#repo = 'prabirshrestha/asyncomplete.vim'
#merged = 0
#
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-lsp.vim'
#merged = 0

# format text
[[plugins]]
repo = 'godlygeek/tabular'

# fuzzy finder
[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install --all
'''

# fzf for vim
[[plugins]]
repo = 'junegunn/fzf.vim'
merged = 0

[[plugins]]
repo = 'previm/previm'

# auto close parentheses
[[plugins]]
repo = 'cohama/lexima.vim'

# resize window size on vim
[[plugins]]
repo = 'simeji/winresizer'

# memo
[[plugins]]
repo = 'glidenote/memolist.vim'

# emmet for vim
[[plugins]]
repo = 'mattn/emmet-vim'

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
		\ 'colorscheme': 'wombat',
		\ 'active': {
			\ 'left': [ ['mode', 'paste'], ['readonly', 'branchName', 'filepath', 'modified'] ]
			\ },
		\ 'component_function':{
			\ 'filepath': 'FilePath',
			\ },
		\ }

	function! FilePath()
		if winwidth(0) > 90
			return expand("%:s")
		else
			return expand("%:t")
		endif
	endfunction

	" # show statusbar
	set laststatus=2
	" # hide --INSERT--
	set noshowmode
'''

# template
[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
let g:sonictemplate_vim_template_dir = ["~/.vim/template"]
'''
# manage session
[[plugins]]
repo = 'skanehira/vsession'

# show git diff
[[plugins]]
repo = 'airblade/vim-gitgutter'

# git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'

# preview for the following Ex commands
[[plugins]]
repo = 'markonm/traces.vim'

# syntax file type vue
[[plugins]]
repo = 'posva/vim-vue'

# syntax file type markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'

# syntax file type toml
[[plugins]]
repo = 'cespare/vim-toml'

# syntax file type fish
[[plugins]]
repo = 'dag/vim-fish'

# make table
[[plugins]]
repo = 'mattn/vim-maketable'

# quickrun buffer source cod
[[plugins]]
repo = 'thinca/vim-quickrun'

# color scheme
[[plugins]]
repo = 'cocopon/iceberg.vim'

# vim help ja
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# translate language
[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'vim-jp/vital.vim'
merged = 0

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/gist-vim'

[[plugins]]
repo = 'tokorom/vim-review'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'skanehira/docker.vim'

[[plugins]]
repo = 'skanehira/docker-compose.vim'

[[plugins]]
repo = 'LeafCage/vimhelpgenerator'

[[plugins]]
repo = 'kshenoy/vim-signature'

#[[plugins]]
#repo = 'shinespark/vim-list2tree'

[[plugins]]
repo = 'skanehira/generatedir.vim'

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'heavenshell/vim-textlint'

[[plugins]]
repo = 'po3rin/vim-gofmtmd'

[[plugins]]
repo = 'skanehira/gql.vim'

[[plugins]]
repo = 'jparise/vim-graphql'

[[plugins]]
repo = 'skanehira/preview-markdown.vim'

[[plugins]]
repo = 'mattn/qiita-vim'

[[plugins]]
repo = 'tweekmonster/helpful.vim'

[[plugins]]
repo = 'gyim/vim-boxdraw'

[[plugins]]
repo = 'tyru/open-browser-github.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'liuchengxu/vista.vim'

[[plugins]]
repo = 'tweekmonster/helpful.vim'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'gyim/vim-boxdraw'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = 0

[[plugins]]
repo = 'skanehira/google-map.vim'
