# GoLang
export GOPATH=$HOME/dev/go
export GOBIN=$GOPATH/bin
export PATH=/usr/local/sbin:$PATH:$GOBIN

# qt
export QT_VERSION=5.10.0
export QT_HOMEBREW=true
export QT_DIR=/usr/local/opt/qt5
export PATH=/usr/local/opt/qt/bin:$PATH

# neovim
export XDG_CONFIG_HOME="$HOME/.config"

# ls -G color
export LSCOLORS=gxfxcxdxbxegedabagacad

# rust
export PATH=$PATH:$HOME/.cargo/bin:/usr/local/bin

# java
export JAVA_HOME=$(/usr/libexec/java_home -v "1.8")
export PATH=${JAVA_HOME}/bin:${PATH}

# alias
alias brew="env PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin brew"
alias ls="ls -G"
alias ll="ls -lhG"
alias la="ls -lahG"
alias npmls="npm ls --depth=0"
alias npmlsg="npm ls --depth=0 -g"
alias npmdist="npm install --save-dev"
alias npmgist="npm install -g"
alias lg='lazygit'
alias dry='docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock moncho/dry'
alias asciicast2gif='docker run --rm -v $PWD:/data asciinema/asciicast2gif'

alias ctags='/usr/local/bin/ctags'

# asciinema rec
function rec() {
    command asciinema rec -t $1
}

function play() {
    command asciinema play $1
}

# If not running interactively, don't do anything
case $- in
    *i*) exec fish;;
      *) return;;
esac

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
