# GHQ settings
export GHQ_ROOT=$HOME/dev

# Go settings
export GOPATH=$HOME/go # for download modules when use asdf-golang
export GOBIN=$HOME/go/bin
export PATH=$GOBIN:$PATH

# path settings
export PATH=/usr/local/bin:$HOME/.deno/bin:$PATH
export XDG_CONFIG_HOME=$HOME/.config

# fzf settings
export FZF_DEFAULT_OPTS='--layout=reverse --inline-info --exit-0 -m --preview "bat  --color=always --style=header,grid --line-range :100 {}"'
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'

# Rust settings
export CARGO_HOME=/Users/skanehira/.asdf/installs/rust/1.56.1
export PATH=$CARGO_HOME/bin:$PATH

# others
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=nvim

case $( uname -s ) in
  Linux) ;;
  Darwin)
    # homebrew settings
    export HOMEBREW_INSTALL_CLEANUP=1
    # asdf settings
    . /opt/homebrew/opt/asdf/libexec/asdf.sh
    # homebrew curl
    export PATH="/opt/homebrew/opt/curl/bin:$PATH"
    export LDFLAGS="-L/opt/homebrew/opt/curl/lib"
    export CPPFLAGS="-I/opt/homebrew/opt/curl/include"
    export PKG_CONFIG_PATH="/opt/homebrew/opt/curl/lib/pkgconfig"
    # chrome-cli
    export CHROME_BUNDLE_IDENTIFIER="com.vivaldi.Vivaldi"
esac
