# Do not load /etc/profile which override $PATH
# Ref: http://karur4n.hatenablog.com/entry/2016/01/18/100000
setopt no_global_rcs
setopt share_history
setopt hist_expand
setopt hist_ignore_dups
setopt append_history

HISTFILE=${HOME}/.zsh_history
HISTSIZE=2000
SAVEHIST=1000

# remove duplicates path
# https://nonylene.hatenablog.jp/entry/2018/07/05/061533
# https://tech.serhatteker.com/post/2019-12/remove-duplicates-in-path-zsh/
typeset -gU PATH

export PATH=/usr/local/bin:$PATH
export GOPATH=$HOME/dev/go
export GOBIN=$GOPATH/bin
export XDG_CONFIG_HOME=$HOME/.config
export HOMEBREW_INSTALL_CLEANUP=1
export LANG=en_US.UTF-8
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info --exit-0 -m"
export FZF_DEFAULT_COMMAND="ag -g ."
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export GHQ_ROOT=$GOPATH/src
export EDITOR=nvim
export GOENV_ROOT=$HOME/.goenv
export PATH=$GOENV_ROOT/bin:$GOBIN:$PATH
export PATH=/opt/homebrew/opt/make/libexec/gnubin/:$PATH
export GOENV_DISABLE_GOPATH=1
export PATH="$PATH:/Users/skanehira/.yarn/bin"
export PATH="$PATH:/Users/skanehira/.deno/bin"
export PATH="/Users/skanehira/.local/bin:$PATH"

eval $(/opt/homebrew/bin/brew shellenv)
eval "$(goenv init -)"

source "$HOME/.cargo/env"
