bindkey -M viins '\er' history-incremental-pattern-search-forward
bindkey -M viins '^?'  backward-delete-char
bindkey -M viins '^A'  beginning-of-line
bindkey -M viins '^B'  backward-char
bindkey -M viins '^D'  delete-char-or-list
bindkey -M viins '^E'  end-of-line
bindkey -M viins '^F'  forward-char
bindkey -M viins '^G'  send-break
bindkey -M viins '^H'  backward-delete-char
bindkey -M viins '^K'  kill-line
bindkey -M viins '^N'  down-line-or-history
bindkey -M viins '^P'  up-line-or-history
bindkey -M viins '^R'  history-incremental-pattern-search-backward
bindkey -M viins '^U'  backward-kill-line
bindkey -M viins '^W'  backward-kill-word
bindkey -M viins '^Y'  yank

function ghq-fzf() {
  local src=$(ghq list | fzf --preview "bat --color=always --style=grid $(ghq root)/{}/README.*")
  if [ -n "$src" ]; then
    BUFFER="cd $(ghq root)/$src"
    zle accept-line
  fi
  zle -R -c
}
zle -N ghq-fzf
bindkey '^g' ghq-fzf

function tmuxpopup() {
	local width='90%'
	local height='90%'
	local name=$(tmux display-message -p -F "#{session_name}")
	if [[ $name =~ 'popup' ]];
	then
		tmux detach-client
	else
		tmux popup -d '#{pane_current_path}' -xC -yC -w$width -h$height -E "tmux attach -t popup || tmux new -s popup"
	fi
}
zle -N tmuxpopup

alias lg=lazygit
alias gs="git status"
alias gl="git log"
alias ll="ls -la"
alias ls="lsd"
alias ll='lsd -la'
alias diff="delta"
alias k="kubectl"
alias d="docker compose"
alias v="nvim"
alias t="terraform"
alias tl="tmux a -t \$(tmux ls | fzf | cut -d \" \" -f 1)"

# enable prompt color
autoload -U colors && colors
export PROMPT="%{$fg[red]%}%n%{$reset_color%}@%{$fg[green]%}%m%{$fg_bold[yellow]%} %3~ %{$reset_color%}$ "

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
