# java 
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

# GoLang
export GOPATH=$HOME/dev/go
export GOBIN=$GOPATH/bin
export PATH=/usr/local/sbin:$PATH:$GOBIN

# nodebrew
export PATH=$HOME/.nodebrew/current/bin:$PATH

# qt
export QT_VERSION=5.10.0
export QT_HOMEBREW=true
export QT_DIR=/usr/local/opt/qt5
export PATH=/usr/local/opt/qt/bin:$PATH

# neovim
export XDG_CONFIG_HOME="$HOME/.config"

# ls -G color
export LSCOLORS=gxfxcxdxbxegedabagacad

# rust
export PATH=$PATH:$HOME/.cargo/bin:/usr/local/bin

# alias
alias brew="env PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin brew"
alias ls="ls -G"
alias ll="ls -lhG"
alias la="ls -lahG"
alias npmls="npm ls --depth=0"
alias npmlsg="npm ls --depth=0 -g"
alias npmdist="npm install --save-dev"
alias npmgist="npm install -g"
alias lg='lazygit'
alias dry='docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock moncho/dry'
alias asciicast2gif='docker run --rm -v $PWD:/data asciinema/asciicast2gif'

# git console
source /usr/local/Cellar/git/2.14.1/etc/bash_completion.d/git-completion.bash
source /usr/local/Cellar/git/2.14.1/etc/bash_completion.d/git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWUPSTREAM=1
GIT_PS1_SHOWSTASHSTATE=1
export PS1='\[\033[1;32m\]\u\[\033[00m\]:\[\033[1;34m\]\w\[\033[1;31m\]$(__git_ps1)\[\033[00m\] \$ '

# vimでC-s,C-qを使用できるようにするため
stty -ixon -ixoff

# vim plugin tagbarを使えるようにする
alias ctags='/usr/local/bin/ctags'

# asciinema rec
function rec() {
    command asciinema rec -t $1
}

function play() {
    command asciinema play $1
}

# If not running interactively, don't do anything
case $- in
    *i*) exec fish;;
      *) return;;
esac

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
